server:
  port: 8501

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbname?createDatabaseIfNotExist=true
    username: username
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  zipkin:
    base-url: http://localhost:9411/

  applicaion:
    name: account-service

  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"


